name: MyCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    #container: 
     # image: node:8
    services:
     nginx:
      image: nginx
      ports: 
        - 8080:80
      

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - run: |
       echo {{ secrets.MYSECRET}}
       node -v
       curl localhost:8080
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
